# Generated by Django 5.0.3 on 2024-04-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
